# Generated by Django 3.0.5 on 2020-05-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
